services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DYNAMODB_ENDPOINT=http://localstack:4566
    ports:
      - '3000:3000'
    volumes:
      - ./uploads:/usr/src/app/uploads
    restart: unless-stopped
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    ports:
      - '4566-4599:4566-4599'
    environment:
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - CLEAR_TMP_FOLDER=0
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"